### ISSUE TITLE
Operator does not appear to be automatically updating when helmValues in ambassadorinstallation is updated

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador-operator#56]
Using `docker.io/datawire/ambassador-operator:v1.2.8`

**Replicate:**

Apply this `AmbassadorInstallation`:

```
---
apiVersion: getambassador.io/v2
kind: AmbassadorInstallation
metadata:
  name: ambassador-default
  namespace: ambassador
spec:
  version: "*"
  helmValues:
    licenseKey:
      createSecret: "false"
    env:
      AMBASSADOR_ID: default
    replicaCount: 1
    service:
      annotations: ""
      type: LoadBalancer
      ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
```

Wait for the operator to spin up the ambassador pods

Update it with this `AmbassadorInstallation` to install the registry
```
---
apiVersion: getambassador.io/v2
kind: AmbassadorInstallation
metadata:
  name: ambassador-default
  namespace: ambassador
spec:
  version: "*"
  helmValues:
    licenseKey:
      createSecret: "false"
    registry:
      create: "true"
    env:
      AMBASSADOR_ID: default
    replicaCount: 1
    service:
      annotations: ""
      type: LoadBalancer
      ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
```

See that the `ambassador-default-registry` is not created as you would expect it to.
