### ISSUE TITLE
Allow Operator to use standard YAML syntax and values

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador-operator#6]
Currently, the Ambassador Operator only supports writing stuff like:
```
helmValues:
  service.ports[0].name: http
  service.ports[0].port: 80
  service.ports[0].targetPort: 8080
```

We should be as user-friendly as possible, and as such, support writing YAML in a more conventional manner:

```
helmValues:
  service:
    ports:
    - name: http
      port: 80
      targetPort: 8080
```

Also, we should not require the user to remember that they need to escape `.` and `,`.

Debugging YAML is difficult enough as it is -- so let's stick with standard conventions as well.
